### ISSUE TITLE
versions not working correctly with s3 file provider

### ISSUE THREAD

**Issue by DaxterM** [pivotalservices/file-downloader-resource#4]
When using the S3 file provider it appears that versions are being ignored when downloading files and only file_pattern: is being processed.  

Given this cf.yml file
```
version: 2.6.3
product: elastic-runtime
file_pattern: cf-*.pivotal
stemcell_product: stemcells-ubuntu-xenial
stemcell_version: "97.34"
stemcell_file_pattern: "bosh-stemcell-*-vsphere-esxi-ubuntu-xenial-go_agent.tgz"
```
with this pivnet-files resource
```
- name: pivnet-files
  type: file-downloader
  source:
    config_provider: git
    path: ((foundation))/versions/
    file_provider: pivnet
    version_root: ((foundation))/versions/
    uri: ((uri)
    private_key: ((configuration.private_key))
    branch: master
    file_provider: s3
    endpoint: ((s3.endpoint))
    bucket: platform-automation-product
    access_key_id: minio
    secret_access_key: password
```

I expected a get on this resource to fail because my s3 bucket does not have version of 2.6.3. Instead the resource matched on platform-automation-product/elastic-runtime/cf-2.3.3-build.10.pivotal which was the only file in that bucket
